version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t pmcwhite/circledemo:0.1 .
            echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin
            docker push pmcwhite/circledemo:0.1
